# Generated by Django 3.1 on 2020-09-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.FloatField(),
        ),
    ]
